name: 'OpenTofu CI/CD Workflow'

on:
  workflow_dispatch:
    inputs:
      demo:
        type: choice
        description: 'Select a demo to run'
        options:
          - 'demo-0'
          - 'demo-1'
          - 'demo-2'
          - 'demo-3'

jobs:
  opentofu-plan:
    name: 'OpenTofu Plan'
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        shell: bash
        working-directory: ./${{ github.event.inputs.demo }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup OpenTofu
      uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: 1.9.1

    - name: OpenTofu Init
      id: init
      run: tofu init
    
    - name: OpenTofu Validate
      id: validate
      run: tofu validate
    
    - name: OpenTofu Plan
      id: plan
      run: tofu plan

  opentofu-apply:
    name: 'OpenTofu Apply'
    runs-on: ubuntu-latest
    needs: opentofu-plan
    environment: dev-approval
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup OpenTofu
      uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: 1.9.1

    - name: OpenTofu Init
      id: init
      run: tofu init
    
    - name: OpenTofu Apply
      id: apply
      run: tofu apply -auto-approve
